# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  user_repository:
    class: AppBundle\Repositories\UserRepository
    factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
    arguments:
      - AppBundle:User

  task_repository:
      class: AppBundle\Repositories\TaskRepository
      factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
      arguments:
        - AppBundle:Task

  user_signup_command_handler:
    class: AppBundle\CommandHandler\UserSignupCommandHandler
    arguments: [ '@user_repository', '@validator', '@security.encoder_factory' ]
    tags:
      - { name: command_handler, handles: AppBundle\Command\UserSignupCommand }

  task_add_command_handler:
    class: AppBundle\CommandHandler\TaskAddCommandHandler
    arguments: [ '@task_repository', '@validator' ]
    tags:
      - { name: command_handler, handles: AppBundle\Command\TaskAddCommand }

  task_update_command_handler:
      class: AppBundle\CommandHandler\TaskUpdateCommandHandler
      arguments: [ '@task_repository', '@validator' ]
      tags:
        - { name: command_handler, handles: AppBundle\Command\TaskUpdateCommand }